### ISSUE TITLE
Issue with integration

### ISSUE THREAD

**Issue by sudhanshuptl** [dharmeshkakadia/presto-event-logger#1]
Hi,
I was trying this iteration and it was not working.
1. where logs will be created?
Is there any way to test in local.

Sorry for Naive question as i am new to java.

**Comment by dharmeshkakadia** [comment]
I am not sure I understand your question. The logs will be created based on log4j.properties

**Comment by sudhanshuptl** [comment]
Actually i tried adding log location , but it was not working.

**Comment by dharmeshkakadia** [comment]
What error do you get?
