### ISSUE TITLE
Jar files

### ISSUE THREAD

**Issue by wajahatahmed245** [dharmeshkakadia/presto-event-logger#2]
![image](https://user-images.githubusercontent.com/32391965/62698324-4c04ff00-b9f6-11e9-8da4-adc76e08d729.png)
![image](https://user-images.githubusercontent.com/32391965/62698350-59ba8480-b9f6-11e9-973f-73b5c3c9c5b1.png)

Hi I am new to java, where can I find these jar files which are required for working of the event -logger

**Comment by dharmeshkakadia** [comment]
Hi, you can download those jars from maven. For example https://mvnrepository.com/artifact/com.google.guava/guava/21.0

**Comment by dharmeshkakadia** [comment]
Feel free to reopen if you still need help.
