### ISSUE TITLE
Provider QueryFileLoggerPlugin not found

### ISSUE THREAD

**Issue by groobyming** [dharmeshkakadia/presto-event-logger#3]
Hello, when I added it to the plugin directory and then started presto, the following error occurred：

![image](https://user-images.githubusercontent.com/34335395/84029313-bf83ee00-a9c4-11ea-84aa-6144a925cd86.png)

**Comment by dharmeshkakadia** [comment]
Looks like an issue with installation or build. How did you do that?

**Comment by groobyming** [comment]
My fault, I write the wrong class name in the spi metadata file
